### PR TITLE
Remove deprecated or obsolete QT4 code

### PR DESCRIPTION
**Pull request by redhatrises**
Updates deprecated QT4 code to QT5 which fixes build failures related to deprecated QT components.

### CODE REVIEW

**Comment by matejak** [comment]
Would you like to add anything to this PR, or can we remove the WIP status?

**Comment by redhatrises** [comment]
@matejak I'd like to update all the QT components and get this passing. There is another component that needs to be updated that I haven't looked at yet.

```
/Users/travis/build/OpenSCAP/scap-workbench/src/MainWindow.cpp:261:35: error: 'screen' is deprecated: Use QScreen [-Werror,-Wdeprecated-declarations]
    move(QApplication::desktop()->screen()->rect().center() - rect().center());
                                  ^

/usr/local/opt/qt/lib/QtWidgets.framework/Headers/qdesktopwidget.h:77:5: note: 'screen' has been explicitly marked deprecated here
    QT_DEPRECATED_X("Use QScreen") QWidget *screen(int screen = -1);
    ^

/usr/local/opt/qt/lib/QtCore.framework/Headers/qglobal.h:294:33: note: expanded from macro 'QT_DEPRECATED_X'
#  define QT_DEPRECATED_X(text) Q_DECL_DEPRECATED_X(text)
                                ^

/usr/local/opt/qt/lib/QtCore.framework/Headers/qcompilerdetection.h:649:55: note: expanded from macro 'Q_DECL_DEPRECATED_X'
#    define Q_DECL_DEPRECATED_X(text) __attribute__ ((__deprecated__(text)))
                                                      ^

1 error generated.
make[2]: *** [CMakeFiles/scap-workbench.dir/src/MainWindow.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/scap-workbench.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by matejak** [comment]
I see, there may be more of those errors. I may be able to help as soon as I get the Fedora 31 setup up and running.

**Comment by redhatrises** [comment]
@matejak I have removed the WIP. All the deprecated QT components are now gone. The build is now failing due a recent change in OpenSCAP at https://github.com/OpenSCAP/openscap/pull/1426/files#diff-48b7ea87d52d90ebded20cfff1f60abcR39

**Comment by matejak** [comment]
Great work, merging - the openscap issue has been resolved as well.

**Comment by redhatrises** [comment]
Sweet! Thanks @matejak and builds are now passing! Even better!

**Pull request merged**
