### PR TITLE
Improve UX of about window

### PR DESCRIPTION
**Pull request by yuumasato**
Links in the description were made clickable.

### CODE REVIEW

**Comment by yuumasato** [comment]
I think the easier way to remove the icon from OK button is by removing all icons from the application, done in PR #89.
An other approach would be by designing the about dialog manually.

**Comment by ybznek** [comment]
changes LGTM, but personally I don't think we still use https://fedorahosted.org/scap-workbench/

cc @mpreisler

**Comment by mpreisler** [comment]
Good catch @ybznek 

Please change the URL to: `https://www.open-scap.org/tools/scap-workbench/`

**Comment by yuumasato** [comment]
URL updated.

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
