### PR TITLE
Add OL7 support to SSGIntegrationDialog

### PR DESCRIPTION
**Pull request by iokomin**
#### Description

Add OL7 content to SSG integration dialog

#### Testing (Oracle Linux 7)
- Built scap-workbench package on top of master and installed on OL7
- Checked OL7 content available for selection and loads expected profiles

#### Notes
I couldn't find target branch policy for this merge, v1-2 selected by default. OL7.5 now uses scap-workbench-1.1.6 while it could be considered next update might switch to v1-2.  If possible and makes sense please merge this change in both v1-1 and v1-2 branches. Let me know if any change or additional PR required.

Signed-off-by: Ilya Okomin <ilya.okomin@oracle.com>

### CODE REVIEW

**Comment by cipherboy** [comment]
@openscap-ci whitelist

**Comment by cipherboy** [comment]
@openscap-ci test this please

**Comment by cipherboy** [comment]
LGTM, I'm fine with this change.

Something to consider for the team, perhaps in the future we should discuss maintaining a larger name set. I'm guessing these abbreviations that we need to support tend to be static (or in the worst case, triggered by a change in SSG).

**Comment by cipherboy** [comment]
Also, welcome to scap-workbench, @iokomin! Travis failure unrelated, (related to [openscap#1161](https://github.com/OpenSCAP/openscap/issues/1161)).

**Comment by iokomin** [comment]
Thanks @cipherboy and thanks for taking your time on review!:)
Luckily there is only minor change required in scap-workbench to support OL7 content.

**Comment by cipherboy** [comment]
Okay, so before:


screenshot from 2018-08-16 09-30-57


and After:

screenshot from 2018-08-16 09-30-19


The one side effect this has is making `OL7` a favorite, so I'll have to defer to @mpreisler on that before merging. In my opinion, I'd rather see `favorite` become a dynamic check -- use `oscap` or some other mechanism to interrogate the current distro and make the current-distro content become favorite. (So on RHEL7, RHEL7 and RHEL-OSP7 become favorites, on OL7 only OL7 is a favorite, etc.)


That's my 2c. though.

**Comment by iokomin** [comment]
@cipherboy noticed behavior possible if all SSG products built for a distro. 
My assumption was that only subset built with just one favorite, e.g. RHEL7 - {rhel7,jre,firefox,..} while on OL7 it would be {ol7,jre,firefox}. Thus no confusion with default favorite observed.
However if some distros build all/wider set of products then yes we need some mechanism to bump up 'platform related favorite' on the top.

**Comment by cipherboy** [comment]
@iokomin See Fedora for instance; all products in SSG are shipped as content in the released `scap-security-guide` for Fedora package:

```
# dnf whatprovides /usr/share/xml/scap/ssg/content/ssg-ol7-ds.xml
Last metadata expiration check: 1:55:35 ago on Thu 16 Aug 2018 10:00:43 AM EDT.
scap-security-guide-0.1.40-1.fc28.noarch : Security guidance and baselines in SCAP formats
Repo        : @System
Matched from:
Filename    : /usr/share/xml/scap/ssg/content/ssg-ol7-ds.xml

scap-security-guide-0.1.40-1.fc28.noarch : Security guidance and baselines in SCAP formats
Repo        : updates
Matched from:
Filename    : /usr/share/xml/scap/ssg/content/ssg-ol7-ds.xml
```

So when I open `scap-workbench` built with your changes:

screenshot from 2018-08-16 11-57-30

I now see `OL7` in the "favorite" list. To me, that favorite does not depend on distro is something that should change too.

**Comment by iokomin** [comment]
@cipherboy Well I agree then that 'favorite's list concept is the subject for review.

From my side I could exclude OL7 from favorites for now, just format name label to uppercase. It will work for us as no other 'favorite's built as part of ol7 ssg package. Will it work for you?

**Comment by cipherboy** [comment]
Per discussion with @mpreisler, we're merging it and dealing with favorites sometime later.

Thanks for the contribution @iokomin and welcome to `scap-workbench`! :)

**Comment by iokomin** [comment]
Thanks for accepting these changes!

**Pull request merged**
