### PR TITLE
MainWindow tab order and SSG Dialog default button

### PR DESCRIPTION
**Pull request by WesleyCeraso**
These two commits fixes the tab order in MainWindow and the default button in SSG Integration Dialog respectively.

### CODE REVIEW

**Comment by yuumasato** [comment]
I noticed that the Rules list is tabbed after the `Scan` button, can it be placed after the `Expand all` button?

Also, something unrelated that I noticed, pressing <Enter> on `Scan` button does nothing, you need to use <Space> to activate it, do you know why?

**Comment by WesleyCeraso** [comment]
@yuumasato The Rules list is in the correct tab order now. About the Scan button I could not reproduce what you described, instead, it always start the scan here.

**Comment by yuumasato** [comment]
@WesleyCeraso Cool. About the `Scan` button, I just noticed that I used weird formatting and github just hid the buttons I mentioned.

**Comment by WesleyCeraso** [comment]
@yuumasato Yes, I know why. When you want to "click" whatever has focus you should press Space. When you press Enter, the default button will be "clicked", howeverm there is no default button in the MainWindow.

I'll make te Scan button the default button.

**Comment by WesleyCeraso** [comment]
Never mind, default button only works inside Dialogs, not MainWindows. There are workarounds, but I don't think they are worthwhile.
That said, you should expect to use the space, not enter.

**Comment by yuumasato** [comment]
> When you want to "click" whatever has focus you should press Space. When you press Enter, the default button will be "clicked",

Interesting.

> Never mind, default button only works inside Dialogs, not MainWindows. There are workarounds, but I don't think they are worthwhile.
That said, you should expect to use the space, not enter.

Ok.

Thank you for these fixes!

**Pull request merged**
