### PR TITLE
Set CMAKE_BUILD_TYPE

### PR DESCRIPTION
**Pull request by redhatrises**

### CODE REVIEW

**Comment by redhatrises** [comment]
Travis is expected to fail for now.

**Comment by mpreisler** [comment]
I am not sold on this ;-D

**Comment by mpreisler** [comment]
Please use your fork instead of pushing to the main repo next time.

**Comment by redhatrises** [comment]
> Please use your fork instead of pushing to the main repo next time.

Oh man! Did I seriously do that!?!?!?! wow.... just wow....

**Pull request merged**
